### ISSUE TITLE
a{sv} parameter current version

### ISSUE THREAD

**Issue by faljse** [sidorares/node-dbus#147]
Tried calling a function with a{sv} signature and failed.:
```
Error: Invalid struct data
    at writeStruct (/opt/webauslage/webauslage/lib/node-dbus/lib/marshall.js:31:11)
    at write (/opt/webauslage/webauslage/lib/node-dbus/lib/marshall.js:45:7)
    at write (/opt/webauslage/webauslage/lib/node-dbus/lib/marshall.js:62:7)
    at writeStruct (/opt/webauslage/webauslage/lib/node-dbus/lib/marshall.js:34:5)
    at module.exports (/opt/webauslage/webauslage/lib/node-dbus/lib/marshall.js:17:13)

```
```
fs.Mount(
        [ // top level struct is js array
        [ // array is js array
            ['fstype', ['s', 'vfat']], // dict_entry is 2 element array - key,value
        ]
        ]
    , (err, objects) => {
```

I saw your comment in marshall.js
```
// TODO: serialise JS objects as a{sv}
//function writeHash(ps, treeKey, treeVal, data) {
```
Does that mean there is no (easy) way in current version?

**Comment by 0xcaff** [comment]
Duplicate of #132

**Comment by sidorares** [comment]
Duplicate of #132, as @0xcaff noted — closing in favour of that one, which has the worked example of how to build the nested `a{sv}` structure by hand.

The underlying ergonomics problem (you should be able to pass a plain JS object) is tracked in [ROADMAP §4.1 / §4.2](https://github.com/sidorares/dbus-native/blob/master/ROADMAP.md#41-variant-handling) together with #3 and #67.
