### ISSUE TITLE
dbus2js crash when inspect dnsmasq

### ISSUE THREAD

**Issue by neophob** [sidorares/node-dbus#148]
I tried to introspect dnsmasq, looks like a missing sanity check

```
node_modules/.bin/dbus2js --bus system --service uk.org.thekelleys.dnsmasq --path /
ifaces0 undefined
/opt/node_modules/dbus-native/node_modules/xml2js/lib/xml2js.js:216
          throw ex;
          ^

TypeError: Cannot read property 'length' of undefined
    at /opt/node_modules/dbus-native/bin/dbus2js.js:59:31
    at Parser.<anonymous> (/opt/node_modules/dbus-native/node_modules/xml2js/lib/xml2js.js:199:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
```

**Comment by sidorares** [comment]
thanks! I don't really know when I have some free time to investigate, can you try to have a look at the problem?

**Comment by sidorares** [comment]
Fixed in #321.

The crash was `dbus2js` indexing straight into an absent `interface` key, which
is what a path exposing only child nodes gives you — dnsmasq's shape exactly.
Reproduced with a service that has nothing at `/` and one object below it:

```
dbus2js --path / exit code: 0 (was: TypeError crash)
stderr: warning: no interfaces at /
```

It now reports the situation and exits cleanly instead of throwing.

Several other things were wrong with `dbus2js` and are fixed in the same
change: `--dump` introspected twice and printed the XML *and* a generated
module into the same stream; missing `--service`/`--path` produced a call with
an undefined destination rather than a usage message; `die()` wrote to stdout,
corrupting the generated module, and exited `-1` (status 255); there was no
timeout, so a service that was present but not answering hung the command
forever; and generated signal handlers used a match rule of
`type='signal',member='X'` with no path or interface, asking the daemon for
that signal name from every service on the bus.

Worth knowing: **`dbus2js` is now deprecated** (`DBUS_DEP0005`) in favour of
`dbus-native types`, which emits TypeScript declarations and does handle
properties and signals. It still works, and running it prints the equivalent
command built from your own arguments:

```
npx dbus-native types --system \
  --service uk.org.thekelleys.dnsmasq \
  --path / \
  --out types.d.ts
```
