### ISSUE TITLE
I got a handshake error

### ISSUE THREAD

**Issue by mikeyqin** [sidorares/node-dbus#158]
I have a problem when I use dbus-native and need your help to trouble shoot. Thanks in advance!

I am running on Ubuntu 16.04 LTS.  D-Bus Message Bus Daemon 1.10.6.  I configured dbus to listen to 5555, and export DBUS_SYSTEM_BUS_ADDRESS=tcp:host=127.0.0.1,port=5555,family=ipv4

When I try to connected via this code:
var dbus = require('dbus-native');
var systembus = dbus.systemBus();

I got 
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (undefined)
    at EventEmitter.emit (events.js:144:17)
    at /home/haba1/node/node_modules/dbus-native/index.js:107:19
    at /home/haba1/node/node_modules/dbus-native/lib/handshake.js:109:22
    at /home/haba1/node/node_modules/dbus-native/lib/handshake.js:29:14
    at FSReqWrap.oncomplete (fs.js:82:15)

Here is my dbus system config
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-Bus Bus Configuration 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <auth>EXTERNAL</auth>
  <auth>ANONYMOUS</auth>
  <listen>tcp:host=*,bind=*,port=5555,family=ipv4</listen>
  <listen>unix:path=/var/run/dbus/system_bus_socket</listen>
  <allow_anonymous/>
  <apparmor mode="disabled"/>
</busconfig>

dbus-send works fine:
$dbus-send --system --print-reply --type=method_call --dest=org.freedesktop.NetworkManager  /org/freedesktop/NetworkManager org.freedesktop.NetworkManager.GetAllDevices
method return time=1505175986.555811 sender=:1.12 -> destination=:1.106 serial=1406 reply_serial=2
   array [
      object path "/org/freedesktop/NetworkManager/Devices/0"
      object path "/org/freedesktop/NetworkManager/Devices/1"
      object path "/org/freedesktop/NetworkManager/Devices/2"
      object path "/org/freedesktop/NetworkManager/Devices/3"

**Comment by sidorares** [comment]
thanks for report @mikeyqin !

Can you help me debugging this? Tha error comes from https://github.com/sidorares/node-dbus/blob/a6ef757feb485d9f9a6367e2dc594fd5a456d1a2/lib/handshake.js#L27

I'm not exactly sure if auth method is correct ( https://dbus.freedesktop.org/doc/dbus-specification.html#auth-mechanisms-sha ) and why error passed is printed as "undefined"

Can you log `filename`, `dirname`,  and error `fs.stat` returns? Plus maybe content of filename and attributes of thet file on your system

**Comment by mikeyqin** [comment]
When that code is executing,
 fs.stat(dirname, function(err, stat) 
I don't have dirname existing on my system, where dirname='/home/(mylogin)/.dbus-keyrings'.

I am wondering, if the handshake is necessary if SSL is not being used -- i don't know where to config dbus to use SSL.

**Comment by mpvader** [comment]
hi, I get that exact same error. I'm also trying to connect to a dbus remotely, using anonous authentication:

```
  const bus = dbus.createClient({
    busAddress: 'tcp:host=192.168.178.57,port=78'
  })
```

from the dbus-conf file on the other host (those three lines in the middle is what I added, and yes only do this in a trusted network.. :smile: ):
```
  <listen>unix:path=/var/run/dbus/system_bus_socket</listen>

  <listen>tcp:host=0.0.0.0,port=78</listen>
  <auth>ANONYMOUS</auth>
  <allow_anonymous/>

  <policy context="default">
```

The file its trying to read is `/home/matthijs/.dbus-keyrings/org_freedesktop_general` and it simply doesn't exist.

The code trying to do the stat are these lines:
```
  var dirname = path.join(getUserHome(), '.dbus-keyrings');
  // > There is a default context, "org_freedesktop_general" that's used by servers that do not specify otherwise.
  if (context.length === 0) context = 'org_freedesktop_general';

  var filename = path.join(dirname, context);
  // check it's not writable by others and readable by user
  fs.stat(dirname, function(err, stat) {
    if (err) return cb(err);
```

Isn't the fix simply to first check that the file exists? I'm not too familiar with fs.stat, but more than happy to make a small patch that fixes this.

Ofcourse in my case I an also work around it by specifying the auth method like this:
```
  const bus = dbus.createClient({
    busAddress: 'tcp:host=192.168.178.57,port=78',
    authMethods: ['ANONYMOUS']
  })
```

**Comment by mpvader** [comment]
ps. the error is this:

```
{ Error: ENOENT: no such file or directory, stat '/home/matthijs/.dbus-keyrings'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/home/matthijs/.dbus-keyrings' }
```

**Comment by sidorares** [comment]
looks lifor some reason it tries DBUS_COOKIE_SHA1 auth

can you add some logging and check 1) if array of auth methods passed correctly at https://github.com/sidorares/dbus-native/blob/e115cc8e8a27670152216a7a7ffc51d643d4abef/lib/handshake.js#L60 2) log each line returned from deamon at https://github.com/sidorares/dbus-native/blob/e115cc8e8a27670152216a7a7ffc51d643d4abef/lib/handshake.js#L80

**Comment by mpvader** [comment]
> looks lifor some reason it tries DBUS_COOKIE_SHA1 auth

Yes, but isnt that by design? Specifying an auth option in the opts indeed gets rid of the error.

See https://github.com/sidorares/dbus-native/blob/e115cc8e8a27670152216a7a7ffc51d643d4abef/lib/constants.js

**Comment by mpvader** [comment]
(I’ve slighty updated above comment, and can do that logging at line 80 tomorrow)

**Comment by mpvader** [comment]
Yes happy to do so. Give me a few days though; I’ll be back here!

**Comment by alager** [comment]
Has this been fixed?  I just cloned the repo and ran the **p2p example** serv.js and cli.js and am getting this same error:
`Error: ENOENT: no such file or directory, stat '/home/aaronl/.dbus-keyrings'`

**Comment by mpvader** [comment]
No; it wasn’t @alager; I’ve been; and still am; completely side tracked since above exchange.

**Comment by sidorares** [comment]
Answered — the unhelpful part of this is fixed.

**What you saw:**

```
Error: Uncaught, unspecified "error" event. (undefined)
```

That is the shape of the bug. The handshake failed, and what it reported was `undefined` — so there was nothing to act on, and no way to tell a rejected auth mechanism from a refused connection from a missing cookie file.

**Today the handshake emits a real `Error` with a message.** Against a server that answers `REJECTED`:

```js
conn.on('error', e => {
  e instanceof Error;   // true
  e.constructor.name;   // 'Error'
  e.message;            // 'cookie not found'
});
```

That is real output from a stub server that rejects the way a daemon does. Whatever the cause, you now get a sentence rather than `undefined`.

**On your actual setup** — `tcp:host=127.0.0.1,port=5555,family=ipv4` — the usual cause is authentication rather than the transport. Over TCP, `EXTERNAL` cannot be used (there are no SO_PEERCRED credentials to pass), so the daemon falls back to `DBUS_COOKIE_SHA1`, which needs a readable `~/.dbus-keyrings/org_freedesktop_general` shared between the two ends. If the daemon runs as a different user than your node process, the cookie is not readable and authentication fails — which in 2017 surfaced as exactly that `(undefined)`.

Two other things have changed since, both relevant:

- `DBUS_COOKIE_SHA1` had a real bug in the response format, fixed in 0.12.0 — a missing space meant the server rejected an otherwise correct reply.
- `getUserHome()` used the regex `/$win/`, which can never match, so the keyring path was wrong on Windows. It uses `os.homedir()` now.

If you are still doing this, `dbus-native introspect --address tcp:host=127.0.0.1,port=5555` will tell you quickly whether it is auth or the socket.

Closing — the `(undefined)` this issue is really about is gone. Please open a new issue if a current version still fails against a TCP daemon; there will be an error message to paste this time.
