### ISSUE TITLE
Implement dbus-send command

### ISSUE THREAD

**Issue by hoigo** [sidorares/node-dbus#56]
I'm a newbie here and I would like to use your d-bus library. I wanted to implement the following call with node-dbus, but I couldn't get it to a successful run:

dbus-send --print-reply --type=method_call --bus='unix:path=/var/run/dbus/my_bus_socket' --dest='de.my.Device' '/de/my/Device/alarm' de.my.common.Alarm.get_alarm_state

Could you give me hint on how to do it?

Thanks in advance!

**Comment by sidorares** [comment]
```js
var dbus = require('dbus-native');
var bus = dbus.sessionBus({socket: '/var/run/dbus/my_bus_socket'});
bus.invoke({
   destination: 'de.my.Device',
   path: '/de/my/Device/alarm',
   interface: 'de.my.common.Alarm',
   member: 'get_alarm_state'
}, function(err, param1, param2, param3) {
  // you get as much parameters here as your response signature indicate
});
```

**Comment by hoigo** [comment]
Does the current version run with Node 0.12.0?

**Comment by sidorares** [comment]
I need to check binary `abstractsocket` module status but if you connect using tcp or normal unix sockets ( usually the case for system bus ) it does work for any node version from 0.6 to 1.6.1 (iojs) as it uses very little of node api ( basically `EventEmitter`, `Buffer` and `net` )

**Comment by hoigo** [comment]
Well, I tried it with Node 0.10 and I got a TypeError. This is the stack trace:

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at EventEmitter.emit (events.js:74:15)
    at /home/node_modules/dbus-native/index.js:93:19
    at /home/node_modules/dbus-native/lib/handshake.js:105:22
    at /home/node_modules/dbus-native/lib/handshake.js:29:14
    at Object.oncomplete (fs.js:107:15)

I logged the error and it says the following:

Error: ENOENT, stat '/root/.dbus-keyrings'

Well, there's no ".dbus-keyrings" folder in the system. Do I need such a directory?

**Comment by sidorares** [comment]
Does dbus-send command work for you? If so, it's a bug in handhake part of this library

**Comment by hoigo** [comment]
Yes, dbus-send works without a problem! Could you provide a bugfix?

**Comment by sidorares** [comment]
I'll need to replicate issue you have

Can you add one line just after `readLine` at https://github.com/sidorares/node-dbus/blob/master/lib/handshake.js#L74 with
```js
    console.log(authMethod, id, line);
```
And post results?

You can edit your local copy in `./node_modules/dbus-native/lib/handshake.js`

**Comment by hoigo** [comment]
Yep, here's the output:

EXTERNAL 30 <Buffer 52 45 4a 45 43 54 45 44 20 45 58 54 45 52 4e 41 4c 20 44 42 55 53 5f 43 4f 4f 4b 49 45 5f 53 48 41 31 20 41 4e 4f 4e 59 4d 4f 55 53 0d>

**Comment by sidorares** [comment]
the buffer part is "'REJECTED EXTERNAL DBUS_COOKIE_SHA1 ANONYMOUS\r'"

thanks, I'm looking into it

**Comment by hoigo** [comment]
did you find something for solving it?

**Comment by sidorares** [comment]
can't reproduce locally - handshake succeeds,  after "EXTERNAL 30\r" I get "OK .." reply ( I started unity root session )

Why are you running your script as root? Do you have dbus session started for root user?

**Comment by hoigo** [comment]
On that system every process is running as root and I started the script as root.

I tried to run your p2p example on a 32-bit Ubuntu system under a user account and I got the same error at the client script.

**Comment by sidorares** [comment]
Splitting the two things in this issue, since the title and the original question are different.

**The original question — how to make that call from JavaScript — is answered**, and the modern form is shorter than the 2015 reply:

```js
const bus = require('dbus-native').sessionBus({ socket: '/var/run/dbus/my_bus_socket' });

const state = await bus.invoke({
  destination: 'de.my.Device',
  path: '/de/my/Device/alarm',
  interface: 'de.my.common.Alarm',
  member: 'get_alarm_state'
});
```

No callback needed — omitting it returns a thenable (0.6). Failures reject with a `DBusError` carrying `dbusName`, `message` and the call site (0.7).

On @hoigo's `ENOENT, stat '/root/.dbus-keyrings'` from further down the thread: that was the `DBUS_COOKIE_SHA1` auth path, and there was a real bug there — `getUserHome()` matched on `/$win/`, a regex that can never match, so the keyring path was wrong. Fixed in 0.5.0.

**The title — an actual `dbus-send` CLI — is still open**, and is a genuinely good first issue. The pieces it would need already exist: `bin/dbus-native.js` has the subcommand plumbing (`types`, `introspect`, `lint`, `codemod`) and `node:util.parseArgs` handles the flags, so it is mostly mapping `--dest`/`--type`/`--print-reply` and the `type:value` argument syntax onto `bus.invoke`. Listed under ROADMAP §5.
