### ISSUE TITLE
direct connection error is not catchable

### ISSUE THREAD

**Issue by chmorgan** [sidorares/node-dbus#80]
Can't seem to figure out how to handle the error reported when the dbus server isn't available. This occurs in the case where the pulseaudio dbus server isn't running (the module hasn't been loaded). Tried using the .on syntax in getPulseAudioClient() but I get exceptions saying that bus doesn't have an .on() function.

npm install q dbus-native

$ node test.js 
initialize
socket path /run/user/1000/pulse/dbus-socket

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ENOENT
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)

```js
"use strict";

var DBUS_PROPERTIES_INTERFACE = 'org.freedesktop.DBus.Properties';

// Parameters used to lookup the bus name of the pulseaudio dbus server
var DBUS_PULSE_INTERFACE = 'org.PulseAudio.ServerLookup1';
var DBUS_PULSE_DESTINATION = 'org.PulseAudio1';
var DBUS_PULSE_PATH = '/org/pulseaudio/server_lookup1';

// Parameters used to itneract with the pulseaudio dbus service
var DBUS_CORE_INTERFACE = 'org.PulseAudio.Core1.Device';
var DBUS_CORE_DESTINATION = 'org.PulseAudio.Core1.Device';
var DBUS_CORE_PATH = '/org/pulseaudio/core1/sink0';

var Q = require('q');

var dbus = require('dbus-native');

var bus = dbus.sessionBus();

var pulseInterface;
var deviceInterface;

/** Typically 65537 */
var VolumeSteps;

/**
 * @return a promise that resolves to the volume steps or rejects with the
 * error value
 */
function getVolumeSteps()
{
    console.log("getVolumeSteps");

    var deferred = Q.defer();

    // retrieve volume steps
    deviceInterface.Get(DBUS_CORE_DESTINATION,
          "VolumeSteps", function(err, result) {
            if(err !== null)
            {
                console.log(err);
                deferred.reject(err);
            } else
            {
                VolumeSteps = result[1][0];
                console.log("VolumeSteps is " + VolumeSteps);
                deferred.resolve(VolumeSteps);
            }
    });

    return deferred.promise;
}

/**
 * @return a promise that resolves to a PulseAudio dbus server client
 * or rejects with an error
 */
function getPulseAudioClient(pulseAudioDbusInterface)
{
    var deferred = Q.defer();

    pulseAudioDbusInterface.Get(DBUS_PULSE_INTERFACE, "Address", function(err, result)
    {
        if(err !== null)
        {
            deferred.reject(err);
        } else
        {
            // strip 'unix:path=' from the start of the string
            var unixSocketPath = result[1][0].replace("unix:path=", "");
            console.log("socket path " + unixSocketPath);

            // connect to the pulseaudio server
            var pulseServerClient = dbus.createClient({
                socket: unixSocketPath,
                direct: true
            });
        }
    });

    return deferred.promise;
}

/**
 * @return A promise that resolves when the initialization is completed or
 * rejects and passes the error to the callback if the initialization has
 * an error.
 */
function initialize()
{
    console.log("initialize");

    var deferred = Q.defer();

    bus.getService(DBUS_PULSE_DESTINATION).getInterface(DBUS_PULSE_PATH,
        DBUS_PROPERTIES_INTERFACE, function(err, iface)
    {
        if (err !== null)
        {
            console.log("bus.getService ", err);
            deferred.reject(err);
        }
        else
        {
            // retrieve the pulseaudio dbus server path
            pulseInterface = iface;

            var pulseServerClientPromise = getPulseAudioClient(pulseInterface);
            pulseServerClientPromise.then(function(paServerClient)
            {
                console.log("retrieving device interface");

                // retrieve the interface for the device
                paServerClient.getService(DBUS_CORE_DESTINATION).getInterface(DBUS_CORE_PATH,
                        DBUS_PROPERTIES_INTERFACE, function(err, iface) {
                    if(err !== null)
                    {
                        console.log("from client service is " + err);
                        deferred.reject(err);
                    } else
                    {
                        console.log("retrieving volume steps");

                        deviceInterface = iface;

                        var volStepsPromise = getVolumeSteps();
                        volStepsPromise.then(function(steps) {
                            VolumeSteps = steps;
                        });
                    }
                });
            });
        };
    });

    return deferred.promise;
}

initialize();
```

**Comment by sidorares** [comment]
you should be able to attach error event to a low level connection - see https://github.com/sidorares/node-dbus/blob/master/index.js#L75

`pulseServerClient.on('error', handleError)`

`createClient()` returns event emitter and the only additional api is `.message({dbus msg data})`, and bus adds rpc/signals/introspection to a client. You can access client as `bus.connection` but in your case you already have reference to it with `pulseServerClient = dbus.createClient()`

**Comment by chmorgan** [comment]
Ahh, I was able to attach an error via:

pulseServerClient.connection.on('error', function()....);

So it must be a bus that is returned from dbus.createClient(), also also confirmed by the exception when using pulseServerClient.on(...) syntax of:

```
$ node patest.js 
initialize
socket path /run/user/1000/pulse/dbus-socket

/home/cmorgan/projects/test/panodetest/patest.js:80
            pulseServerClient.on('error', function() { console.log("some error
                              ^
TypeError: Object #<bus> has no method 'on'
    at Object.<anonymous> (/home/cmorgan/projects/test/panodetest/patest.js:80:31)
    at EventEmitter.<anonymous> (/home/cmorgan/projects/test/panodetest/node_modules/dbus-native/lib/bus.js:113:26)
    at EventEmitter.emit (events.js:95:17)
    at /home/cmorgan/projects/test/panodetest/node_modules/dbus-native/index.js:98:12
    at Socket.<anonymous> (/home/cmorgan/projects/test/panodetest/node_modules/dbus-native/lib/message.js:53:9)
    at Socket.emit (events.js:117:20)
```

**Comment by chmorgan** [comment]
Thank you again man.

**Comment by sidorares** [comment]
yes, you are right. Naming is a bit confusing: `createConnection()` creates connection and `createClient()` creates "bus" - https://github.com/sidorares/node-dbus/blob/master/index.js#L131

**Comment by chmorgan** [comment]
Should we consider changing the names of those functions? I could submit a
pr if I knew what we wanted there.
