### ISSUE TITLE
Connecting to session bus requests password

### ISSUE THREAD

**Issue by JetForMe** [sidorares/node-dbus#96]
I'm not sure exactly what's going on. I try to connect using the following code

	console.log("Connecting to sessionBus 'unix:path=" + process.env.DBUS_LAUNCHD_SESSION_BUS_SOCKET.toString() + "'");
	bus = dbus.sessionBus({ busAddress : "unix:path=" + process.env.DBUS_LAUNCHD_SESSION_BUS_SOCKET.toString() });

and it outputs

    Connecting to sessionBus 'unix:path=/private/tmp/com.apple.launchd.y24Av06XkO/unix_domain_listener'
    Password:PodtiqueUI listening on http://localhost:8080
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: connect ECONNREFUSED
        at exports._errnoException (util.js:746:11)
        at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

You can see it asking for the root password there. If instead I launch node with sudo, I get:

    $ sudo node app.js 
    Password:
    /Users/rmann/Projects/Podtique/podtique/ui/node_modules/dbus-native/index.js:25
      if (!busAddress) throw new Error('unknown bus address');
                             ^
    Error: unknown bus address
        at createStream (/Users/rmann/Projects/Podtique/podtique/ui/node_modules/dbus-native/index.js:25:26)
        at createConnection (/Users/rmann/Projects/Podtique/podtique/ui/node_modules/dbus-native/index.js:70:30)
        at Function.module.exports.createClient (/Users/rmann/Projects/Podtique/podtique/ui/node_modules/dbus-native/index.js:130:20)
        at Function.module.exports.sessionBus (/Users/rmann/Projects/Podtique/podtique/ui/node_modules/dbus-native/index.js:141:25)
        at Object.<anonymous> (/Users/rmann/Projects/Podtique/podtique/ui/app.js:28:13)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)

I'd rather not launch as root, and the OS X launchd dbus-daemon process is loaded not as root.

What's weird is this stuff used to work, but I can't figure out what's changed to break it.

**Comment by sidorares** [comment]
> You can see it asking for the root password there

I don't see it

> If instead I launch node with sudo

launchd probably does not set DBUS_LAUNCHD_SESSION_BUS_SOCKET for root

**Comment by JetForMe** [comment]
The second line of the output in the non-root launch case is

    Password:PodtiqueUI listening on http://localhost:8080

The connection is refused. I'm not sure if that's because of how launchd is opening the socket, or what, but it's owned by my user and has a+rw perms.

The code now is:

	console.log("Connecting to sessionBus 'unix:path=" + process.env.DBUS_LAUNCHD_SESSION_BUS_SOCKET.toString() + "'");
	bus = dbus.sessionBus({ socket : process.env.DBUS_LAUNCHD_SESSION_BUS_SOCKET });

and the output is

	$ node app.js 
	Connecting to sessionBus 'unix:path=/private/tmp/com.apple.launchd.y24Av06XkO/unix_domain_listener'
	Password:PodtiqueUI listening on http://localhost:8080
	events.js:85
		  throw er; // Unhandled 'error' event
				^
	Error: connect ECONNREFUSED
		at exports._errnoException (util.js:746:11)
		at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

Again, you can see something is asking for a password, but an exception is thrown and node exits before I can type it. Also, at this point, my terminal is kinda hosed (no local echo).

**Comment by JetForMe** [comment]
I realized I had a really confused node installation, tried to clean it up. Now I'm on node 4.2.1. I still have the same basic problem:

	$ node app.js 
	Connecting to sessionBus 'unix:path=/private/tmp/com.apple.launchd.y24Av06XkO/unix_domain_listener'
	Password:PodtiqueUI listening on http://localhost:8080
	events.js:141
		  throw er; // Unhandled 'error' event
		  ^

	Error: connect ECONNREFUSED /private/tmp/com.apple.launchd.y24Av06XkO/unix_domain_listener
		at Object.exports._errnoException (util.js:874:11)
		at exports._exceptionWithHostPort (util.js:897:20)
		at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

**Comment by sidorares** [comment]
Answered — macOS session-bus discovery is handled properly now.

**What was going wrong.** On macOS the session bus is advertised through *launchd*, not through `DBUS_SESSION_BUS_ADDRESS`, and `DBUS_LAUNCHD_SESSION_BUS_SOCKET` is set per-user in the launchd environment. Two consequences you hit:

- Under `sudo`, root's environment has no `DBUS_LAUNCHD_SESSION_BUS_SOCKET`, so the library fell through to `throw new Error('unknown bus address')`. @sidorares called that correctly at the time.
- Building the address by hand from `process.env` only works when your process happens to have inherited the variable — which is exactly the fragility that made this "used to work" and then stop.

**Today `sessionBus()` takes no arguments on macOS.** It defaults to `launchd:env=DBUS_LAUNCHD_SESSION_BUS_SOCKET` and resolves it with `launchctl getenv`, falling back to this process's own environment when launchd has no answer. Real output on a Mac just now:

```js
const bus = dbus.sessionBus();   // no busAddress, no env fiddling
await bus.getId();
bus.name;   // ':1.0'
```

```
#96  platform: darwin
#96  sessionBus() connected, unique name: :1.0
```

Because the lookup goes through `launchctl`, it works under `sudo` too — root asks launchd rather than relying on an inherited variable.

**And when the bus genuinely is not running**, you now get a diagnosis instead of `ECONNREFUSED`:

```
launchd address names DBUS_LAUNCHD_SESSION_BUS_SOCKET, which is set neither
in the launchd environment nor in this process. Is dbus running?
(brew services start dbus)
```

That is verbatim, from this machine with dbus stopped.

**On the `Password:` prompt** — that was not this library. Nothing here shells out or reads a password; @sidorares said he could not see where it came from and he was right. It will have been your own app or something else in the process.

Closing. Sorry it took this long; macOS support was genuinely broken for the case you described.
